# Generated by Django 4.2.7 on 2023-11-18 21:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='send_time',
        ),
        migrations.AddField(
            model_name='mailing',
            name='completion_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 18, 21, 44, 17, 449658, tzinfo=datetime.timezone.utc), verbose_name='завершение рассылки'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='emails',
            field=models.ManyToManyField(to='main.client', verbose_name='Клиенты'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='last_sent',
            field=models.DateTimeField(blank=True, null=True, verbose_name='последняя отправка'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 18, 21, 44, 17, 449533, tzinfo=datetime.timezone.utc), verbose_name='старт рассылки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.CharField(choices=[('created', 'Создана'), ('started', 'Запущена'), ('completed', 'Завершена')], default='created', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='maillogs',
            name='last_sent',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата и время последней рассылки'),
        ),
    ]
